spring:
  h2:
    console:
      enabled: true #H2 Console : database UI
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  profiles:
    include:
      - oauth
      - logback